app/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
            
class SearchForm(FlaskForm):
    class Meta:
        csrf = False
    search = StringField('Search', validators=[DataRequired()])
    submit = SubmitField('Search')
    

app/__init__.py
from flask import Flask
from config import Config
from flask_login import LoginManager #for logging users in and maintaining a session
from flask_sqlalchemy import SQLAlchemy #this talk to our database for us
from flask_migrate import Migrate #Makes altering the Database a lot easier

# init Login Manager
login = LoginManager()
#where to be sent if you are not logged in
login.login_view = 'auth.login'
login.login_message = "You must be logged in to view this page"
login.login_message_category = "warning"
# init the database from_object
db = SQLAlchemy()
# init Migrate
migrate = Migrate()

def create_app(config_class=Config):

    app = Flask(__name__)
    app.config.from_object(config_class)
    login.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)

    from .blueprints.main import bp as main_bp
    app.register_blueprint(main_bp)

    from .blueprints.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    return app

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main',__name__,url_prefix='')

from .import routes

app/blueprints/main/routes.py
from flask import g, render_template, request, flash
import requests
from .forms import SearchForm
from flask_login import login_required
from .import bp as main

#Routes
@main.route('/', methods=['GET'])
def index():
    form = SearchForm()
    g.form=form
    return render_template('index.html.j2')

@main.route('/pokemon', methods=['GET', 'POST'])
@login_required
def pokemon():
    form = SearchForm()
    g.form=form
    if request.method == 'POST' and g.form.validate_on_submit():
        pokemon = form.search.data
        url = f'https://pokeapi.co/api/v2/pokemon/{pokemon}'
        response = requests.get(url)
        if response.ok:
            try:
                data = response.json().get("stats")
                spritedata = response.json()["sprites"]['other']['dream_world'].get("front_default")
            except:
                flash('There is no info for {pokemon}', 'warning')
                return render_template("pokemon.html.j2", form=form)
            all_stats = []
            for stat in data:
                stat_dict={
                    'poke_statbase':stat['base_stat'],
                    'poke_stateffort':stat['effort'],
                    'poke_statname':stat['stat']['name'],
                }
                all_stats.append(stat_dict)
            return render_template("pokemon.html.j2", form=form, stats=all_stats, sprite=spritedata, pokemon=pokemon.title())
        else:
            flash('Invalid Pokemon name!', 'danger')
            return render_template("pokemon.html.j2", form=form)
    return render_template("pokemon.html.j2", form=form)   
#export/set FLASK_APP=app.py
#export/set FLASK_ENV=development

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- fav icons -->
    <link rel="shortcut icon" href="{{url_for('static',filename='images/favicon.ico')}}" type="image/x-icon">
    <link rel="apple-touch-icon" sizes="180x180" href="{{url_for('static',filename='images/apple-touch-icon.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static',filename='images/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static',filename='images/favicon-16x16.png')}}">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='css/main.css')}}">
    {% block css %}
    {% endblock %}
    <title>Pokemon Search</title>
  </head>
    <body>
      {% include './includes/nav.html' %}
      <!-- this is a function that's built into flask-->
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages%}
          {% for class, message in messages %}
          <div class="alert alert-{{class}} alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      <div class="container">
          {% block content %}
          
          {% endblock %}
      </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand"><img src="{{url_for('static',filename='pokemon.png')}}" class="logo"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.index')}}">Home</a>
          </li>
          {% if current_user.is_authenticated %}

          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.register')}}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
          </li>
          {% endif %}
      </ul>
    {% if current_user.is_authenticated %}
      <ul class="navbar-nav ms-auto">
      <!-- get from func name -->
      <form class="d-flex" action="{{url_for('main.pokemon')}}" method="POST">
        {{ g.form.hidden_tag() }}
        {{ g.form.search(class="form-control me-2") }}
        {{ g.form.submit(class="btn btn-outline-success") }}
      </form>
      <!-- <form class="d-flex" action="/pokemon" method="POST">
        <a class="navbar-brand"><img src="{{url_for('static',filename='icon.png')}}" class="icon"></a>
        <input name="pokemon" class="form-control me-2" id="pokemon" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> -->
      <li style=" margin-right: 33px;"></li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.edit_profile')}}">
            <img src="https://avatars.dicebear.com/api/gridy/{{current_user.icon}}.svg" style="height:33px;">
          </a>
        </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.logout')}}">
              <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-power" viewBox="0 0 16 16">
                <path d="M7.5 1v7h1V1h-1z"/>
                <path d="M3 8.812a4.999 4.999 0 0 1 2.578-4.375l-.485-.874A6 6 0 1 0 11 3.616l-.501.865A5 5 0 1 1 3 8.812z"/>
              </svg>
            </a>
          </li>

    {% endif %}
      </ul>
    </div>
  </div>
</nav>

app/templates/index.html.j2
{% extends 'base.html' %}
{% block css %}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
{% block title %}
Fakebook
{% endblock %}
{% block content %}
    <div class='indexcontent'>
        <div class='indexcontainer'>
          <div class='right_top'>

            </div>  
          <div class='left_bottom'>
        {% if current_user.is_authenticated %}
                <h3>Hello, {{current_user.first_name}}!</h3><br>
        {% else %}
        {% endif %}
        <img src="{{url_for('static',filename='group.jpg')}}" class="catch"><br /><br />
        {% if current_user.is_authenticated %}
        <h5>Pokemon Search:</h5>
                You can use the search field below to search for all 898 Pokemon.<br />
        <form class="d-flex" action="{{url_for('main.pokemon')}}" method="POST">
        {{ g.form.hidden_tag() }}
        {{ g.form.search(class="form-control me-2") }}
        {{ g.form.submit(class="btn btn-outline-success") }}
        </form>
        {% else %}
        <h5 style="text-align: center;">You must log in before using the search feature.<br /><br />
        <a href="{{url_for('auth.login')}}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Login</a>
</h5>

        {% endif %}
            </div>
            
        </div>
    </div>
{% endblock %}

app/templates/login.html.j2
{% extends 'base.html' %}
{% block title %}
Login
{% endblock %}
    {% block css%}
        {# custom css for page #}
    {%endblock%}
{% block content %}
<h1>Login</h1>
<small style="color:red">{{error}}</small>

<form action="{{url_for('auth.login')}}" method="POST">
  {{ form.hidden_tag() }}
  {# email section #}
  {{ form.email.label(class="form-label") }}
  {{ form.email(class="form-control") }}
  {# email errors #}
  {% for error in form.email.errors %}
   {{ error }}
  {% endfor %}
  {# password section #}
  {{ form.password.label(class="form-label") }}
  {{ form.password(class="form-control") }}
  {# submit section #}
  {{ form.submit(class="btn btn-primary") }}
</form>





{% endblock %}

app/templates/pokemon.html.j2
{% extends 'base.html' %}
{% block css %}
<link rel="stylesheet" href="{{url_for('static',filename='css/pokemon.css')}}">
{% endblock %}
{% block title %}
Pokemon API Lookup
{% endblock %}
{% block content %}

{% if error %}
<div class="container error">
  <div class="row align-items-start">
  <div class="col">
    <h3><img src="{{url_for('static',filename='hobo.png')}}"><br /><br />{{error}}</h3>
    <p>Check your spelling and give it a try again...</p>
    <form class="d-flex" action="{{url_for('main.pokemon')}}" method="POST">
      {{ g.form.hidden_tag() }}
      {{ g.form.search(class="form-control me-2") }}
      {{ g.form.submit(class="btn btn-outline-success") }}
    </form>
  </div>
  <div class="col"></div>
</div>
{% else %}
    <div class='pokemoncontent'>
        <div class='pokemoncontainer'>
          <div class='right_top'>
      {% if sprite %}
        <img src="{{sprite}}" class="pokesprite">
      {% endif %}
            </div>  
          <div class='left_bottom'>
    <div id="rcorners3">
    <div id="content">
      {% if stats %}
    <h1 style="text-align: center; margin-bottom: 33px;">
      {{pokemon}} Stats
    </h1>
  <table class="table table-striped table-hover pokestats">
    <thead>
      <tr>
        <th scope="col">Stat</th>
        <th scope="col">Base</th>
        <th scope="col">Effort</th>
      </tr>
    </thead>
    <tbody>
    {% for stat in stats %}
      <tr>
        <th scope="row">{{stat['poke_statname']}}</th>
        <td>{{stat['poke_statbase']}}</td>
        <td>{{stat['poke_stateffort']}}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endif %}
</div>
</div>
            </div>
            
        </div>
    </div>
  {% endif %}
{% endblock %}

app/templates/register.html.j2
{% extends 'base.html' %}
  {% block css %}
  <link rel="stylesheet" href="{{url_for('static',filename='css/register.css')}}">
  {% endblock %}
  {% block title %}
  Register - Enter Details
  {% endblock %}
{% block content %}
{% if current_user.is_authenticated %}
<h2>Editing {{current_user.first_name}}'s Profile</h2><br>
{% else %}
<h1>Register</h1><br>
{% endif %}
    <div class='registercontent'>
        <div class='registercontainer'>
          <div class='right_top'>
                  {% if current_user.is_authenticated %}
    <div style="text-align: center; font-size: 18px; font-style: italic; margin-bottom: 20px;">Your Current Avatar:<br>
    <img src="https://avatars.dicebear.com/api/gridy/{{current_user.icon}}.svg" style="height:150px; margin-left: 18px;"></div>
  {% endif %}
            </div>  
          <div class='left_bottom'>
<small style="color:red">{{error}}</small>

<form action="{{url_for('auth.edit_profile') if current_user.is_authenticated else url_for('auth.register')}}" method="POST">
  {{ form.hidden_tag() }}

  {# icon section #}
  <div>
    {{form.icon.label}}
  </div><br>
  
  <div class="reg-avatars">
  {% for subfield in form.icon %}
  {{subfield}}
    {{subfield.label | safe}}
  {% endfor %}
    </div>
  <br><br>
    {% for error in form.icon.errors %}
   {{ error }}
  {% endfor %}
  
  {# first_name section #}
  {{ form.first_name.label(class="form-label") }}
  {{ form.first_name(class="form-control", value=current_user.first_name) }}
<br>
  {# last_name section #}
  {{ form.last_name.label(class="form-label") }}
  {{ form.last_name(class="form-control", value=current_user.last_name) }}
<br>
  {# email section #}
  {{ form.email.label(class="form-label") }}
  {{ form.email(class="form-control", value=current_user.email) }}

  {# email errors #}
  {% for error in form.email.errors %}
   {{ error }}
  {% endfor %}
<br>
  {# password section #}
  {{ form.password.label(class="form-label") }}
  {{ form.password(class="form-control") }}
<br>
  {# password section #}
  {{ form.confirm_password.label(class="form-label") }}
  {{ form.confirm_password(class="form-control") }}

  {# password errors #}
  {% for error in form.confirm_password.errors %}
   {{ error }}
  {% endfor %}
<br>
  {# submit section #}
  {{ form.submit(class="btn btn-primary") }}
</form>
            </div>
            
        </div>
    </div>




{% endblock %}

app/templates/students.html.j2
{% extends 'base.html' %}
{% block title %}
My Students
{% endblock %}
{% block content %}
    <h1>Here are all the students in our class:</h1>
    <ul class="list-group">
        {% for student in students %}
            <li class="list-group-item">{{ student }}</li>
        {% endfor %}
    </ul>
{% endblock %}